# **Tic Tac Toe Player vs Computer**

In [ ]:
import sys
import numpy as np
import random
import copy
from collections import deque


The class game from before is used with inclusion of 2 functions get_state and find_open- to get all the open postions on the board.

In [ ]:
class game:

  def __init__(self):
    self.board = np.array([[0, 0, 0],
                            [0, 0, 0],
                            [0, 0, 0]])

    
  def set_item(self, index, player):
    
    if (self.board[index // 3][index % 3]==0):
      self.board[index // 3][index % 3] = player
    else:
      raise RuntimeError('Spot {} already has a piece'.format(index))
  
  def get_state(self):
    return (self.board)

  def show(self):
    print(self.board)
  
  def find_open(self):
    o=[]
    for x in range(len(self.board)):
      for y in range(len(self.board)):
        if self.board[x][y]==0:
          t=x*3+y
          o.append(t)
    return o


  def row_win(self, player):
    for x in range(len(self.board)):
        win = True
          
        for y in range(len(self.board)):
            if self.board[x, y] != player:
                win = False
                break
                  
        if win == True:
            return(win)
    return(win)

  def col_win(self, player):
      for x in range(len(self.board)):
          win = True
            
          for y in range(len(self.board)):
              if self.board[y][x] != player:
                  win = False
                  break
                    
          if win == True:
              return(win)
      return(win)

  def diag_win(self, player):
      win = True
      y = 0
      for x in range(len(self.board)):
          if self.board[x, x] != player:
              win = False
      if win:
          return win
      win = True
      if win:
          for x in range(len(self.board)):
              y = len(self.board) - 1 - x
              if self.board[x, y] != player:
                  win = False
      return win

  # Evaluates whether there is
  # a winner or a tie
  def evaluate(self,player):
      winner = 0
        
      if (self.row_win(player) or self.col_win(player) or self.diag_win(player)):
          winner = player
          
      if np.all(self.board != 0) and winner == 0:
          winner = -1
      return winner  

A dictionary of all the possible states and their respective values is initialized

In [ ]:
Tic=game()
vdict={}
for a in range (3):
  for b in range (3):
    for c in range (3):
      for d in range (3):
        for e in range (3):
          for f in range (3):
            for g in range (3):
              for h in range (3):
                for i in range (3):
                  Tic.board=np.array([[a, b, c],
                                      [d, e, f],
                                      [g, h, i]])
                  if (Tic.evaluate(2)==2):
                    vdict[tuple(Tic.board.flatten())]=1
                  elif (Tic.evaluate(2)==1):
                    vdict[tuple(Tic.board.flatten())]=0
                  else:
                    vdict[tuple(Tic.board.flatten())]=0.5
Tic.__init__()


Explotit function is used to make the move with the highest value

In [ ]:
def exploit(Tic):
  temp=game()
  temp.board=copy.deepcopy(Tic.get_state())
  spots=Tic.find_open()
  v=vdict[tuple(temp.board.flatten())]
  move=0
  for s in spots:
    temp.board=copy.deepcopy(Tic.get_state())
    temp.set_item(s,2)
    if (vdict[tuple(temp.board.flatten())]>= v):
      v=vdict[tuple(temp.board.flatten())]
      move=s
  return (move)

print(exploit(Tic))

8


Explore function is used to make a randomized move so we can explore the environment

In [ ]:
def explore(Tic):
  spots=Tic.find_open()
  s=random.randint(0,len(spots)-1)
  return(spots[s])

print(explore(Tic))

1


Temporal difference learning is used to update our value dictionary by using the state before and the current state

In [ ]:
def update_value(states,vdict):
  alpha=0.1
  v=vdict[tuple(states[0].flatten())]
  vn=vdict[tuple(states[1].flatten())]
  vnew= v + alpha*(vn-v)
  return(vnew)


The helper methods used are explined above.

The feedback needed is the current state of the board which can be used to compute the value of the state.

The action space is the free spaces in the board.

We can see that as we continue to play against the computer the value function which is in the form of a dictionery gets optimized allowing the computer to take better decision.

In [ ]:
play=True
Tic.__init__()
def player1():
  move = int(input("Pick a spot to place 1: (0-8) "))
  return move

def player2():
  move = int(input("Pick a spot to place 2: (0-8) "))
  return move

print('the game started')
s_old=Tic.board

while (play):
  Tic.show()

  move=player1()
  Tic.set_item(move,1)

  if (Tic.evaluate(1)==1):
    print('player 1 is the winner')
    Tic.show()
    break
  elif (Tic.evaluate(1)==-1):
    print('the game is a draw')
    Tic.show()
    break

  Tic.show()
  r=random.randint(1,6)
  if r==1:
    move=explore(Tic)
  else:
    move=exploit(Tic)

  print('computer played-')
  #move=player2()
  Tic.set_item(move,2)
  s_new=Tic.board
  vdict[tuple(s_old.flatten())]=update_value([s_old,s_new],vdict)
  s_old=s_new

  if (Tic.evaluate(2)==2):
    print('player 2 is the winner')
    Tic.show()
    break
  elif (Tic.evaluate(2)==-1):
    print('the game is a draw')
    Tic.show()
    break
  

the game started
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Pick a spot to place 1: (0-8) 5
[[0 0 0]
 [0 0 1]
 [0 0 0]]
computer played-
[[0 0 0]
 [0 0 1]
 [0 0 2]]
Pick a spot to place 1: (0-8) 7
[[0 0 0]
 [0 0 1]
 [0 1 2]]
computer played-
[[0 0 0]
 [0 0 1]
 [2 1 2]]
Pick a spot to place 1: (0-8) 4
[[0 0 0]
 [0 1 1]
 [2 1 2]]
computer played-
[[0 0 0]
 [2 1 1]
 [2 1 2]]
Pick a spot to place 1: (0-8) 0
[[1 0 0]
 [2 1 1]
 [2 1 2]]
computer played-
[[1 2 0]
 [2 1 1]
 [2 1 2]]
Pick a spot to place 1: (0-8) 2
the game is a draw
[[1 2 1]
 [2 1 1]
 [2 1 2]]
