# **Tic Tac Toe Player vs Player**

In [ ]:
import sys
import numpy as np

A class is created called game that can store the state of the board. It can be reset by using the __init__ function.

Each player can input their pieces using the set_item function. finally the evaluate function is used to see if a player or won or the game is a draw.

In [ ]:
class game:

  def __init__(self):
    self.board = np.array([[0, 0, 0],
                            [0, 0, 0],
                            [0, 0, 0]])

    
  def set_item(self, index, player):
    
    if (self.board[index // 3][index % 3]==0):
      self.board[index // 3][index % 3] = player
    else:
      raise RuntimeError('Spot {} already has a piece'.format(index))


  def show(self):
    print(self.board)

  def row_win(self, player):
    for x in range(len(self.board)):
        win = True
          
        for y in range(len(self.board)):
            if self.board[x, y] != player:
                win = False
                break
                  
        if win == True:
            return(win)
    return(win)

  def col_win(self, player):
      for x in range(len(self.board)):
          win = True
            
          for y in range(len(self.board)):
              if self.board[y][x] != player:
                  win = False
                  break
                    
          if win == True:
              return(win)
      return(win)

  def diag_win(self, player):
      win = True
      y = 0
      for x in range(len(self.board)):
          if self.board[x, x] != player:
              win = False
      if win:
          return win
      win = True
      if win:
          for x in range(len(self.board)):
              y = len(self.board) - 1 - x
              if self.board[x, y] != player:
                  win = False
      return win

  # Evaluates whether there is a winner or a tie
  def evaluate(self,player):
      winner = 0
        
      if (self.row_win(player) or self.col_win(player) or self.diag_win(player)):
          winner = player
          
      if np.all(self.board != 0) and winner == 0:
          winner = -1
      return winner  

In [ ]:
play=True
Tic=game()
def player1():
  move = int(input("Pick a spot to place 1: (0-8) "))
  return move

def player2():
  move = int(input("Pick a spot to place 2: (0-8) "))
  return move

print('the game started')

while (play):
  Tic.show()
  move=player1()
  Tic.set_item(move,1)
  if (Tic.evaluate(1)==1):
    print('player 1 is the winner')
    Tic.show()
    break
  elif (Tic.evaluate(1)==-1):
    print('the game is a draw')
    Tic.show()
    break

  Tic.show()
  move=player2()
  Tic.set_item(move,2)
  if (Tic.evaluate(2)==2):
    print('player 2 is the winner')
    Tic.show()
    break
  elif (Tic.evaluate(2)==-1):
    print('the game is a draw')
    Tic.show()
    break


the game started
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Pick a spot to place 1: (0-8) 0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Pick a spot to place 2: (0-8) 2
[[1 0 2]
 [0 0 0]
 [0 0 0]]
Pick a spot to place 1: (0-8) 3
[[1 0 2]
 [1 0 0]
 [0 0 0]]
Pick a spot to place 2: (0-8) 1
[[1 2 2]
 [1 0 0]
 [0 0 0]]
Pick a spot to place 1: (0-8) 6
player 1 is the winner
[[1 2 2]
 [1 0 0]
 [1 0 0]]
